name: Process Record Submission

on:
  issues:
    types: [opened, reopened]

jobs:
  process:
    uses: TouchSudoku/TouchSudoku.github.io/.github/workflows/process-record.yml@records
    secrets: inherit
    permissions:
      contents: write
      issues: write
